sudo: true
language: python
env:
  matrix:
    - MODULE=services/authproxy CXX=g++-4.8 NODE=1
    - MODULE=packages/python/authproxy-client CXX=g++-4.8 NODE=1
before_install:
  - '[ "$NODE" != "" ] && . $HOME/.nvm/nvm.sh'
  - '[ "$NODE" != "" ] && nvm install stable'
  - '[ "$NODE" != "" ] && nvm use stable'
  # See https://github.com/travis-ci/travis-ci/issues/538
  - '[ "$CXX" != "" ] && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y'
  - '[ "$CXX" != "" ] && sudo apt-get update -qq'
  - '[ "$CXX" != "" ] && sudo apt-get install -qq $CXX'
install:
  - bash -c "cd $MODULE; ./travis/install.sh"
before_script:
  - bash -c "cd $MODULE; ./travis/before_script.sh"
script:
  - bash -c "cd $MODULE; ./travis/script.sh"
after_script:
  - bash -c "cd $MODULE; ./travis/after_script.sh"
services:
  - couchdb
