# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('token', models.UUIDField(unique=True)),
                ('token_password', models.BinaryField(max_length=16)),
                ('account_type', models.CharField(max_length=32)),
                ('account_info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
