# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenmrsConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.TextField()),
                ('uuid', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OpenmrsCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OpenmrsInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
                ('name', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='openmrscredential',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmrs.OpenmrsInstance'),
        ),
        migrations.AddField(
            model_name='openmrsconcept',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmrs.OpenmrsInstance'),
        ),
    ]
