# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import json


class Migration(migrations.Migration):

    dependencies = [
        ('openmrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openmrsconcept',
            name='id',
        ),
        migrations.AddField(
            model_name='openmrsconcept',
            name='answers',
            field=models.ManyToManyField(to='openmrs.OpenmrsConcept'),
        ),
        migrations.AddField(
            model_name='openmrsconcept',
            name='concept_class',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openmrsconcept',
            name='datatype',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openmrsconcept',
            name='descriptions',
            field=models.TextField(default='[]', validators=(json.dumps,)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openmrsconcept',
            name='names',
            field=models.TextField(default='[]', validators=(json.dumps,)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openmrsconcept',
            name='retired',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openmrsconcept',
            name='uuid',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
