# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motechmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default='95849aa9-96e3-44a6-9254-c995800ded54'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagerun',
            name='state',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], max_length=9),
        ),
    ]
