# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motechmessages', '0002_auto_20170316_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerun',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
