# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170314_2301'),
        ('motechmessages', '0004_auto_20170316_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRunJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], max_length=9)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.RenameModel(
            old_name='MessageRunArtifact',
            new_name='MessageRunJobArtifact',
        ),
        migrations.RemoveField(
            model_name='messagerun',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='messagerun',
            name='state',
        ),
        migrations.AlterField(
            model_name='messagerunjobartifact',
            name='message_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motechmessages.MessageRunJob'),
        ),
        migrations.AddField(
            model_name='messagerunjob',
            name='message_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motechmessages.MessageRun'),
        ),
    ]
