# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0002_auto_20170310_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javascript', models.TextField()),
                ('filter', jsonfield.fields.JSONField(default=dict)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.Stream')),
            ],
        ),
    ]
