# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 22:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='rev',
            field=models.PositiveIntegerField(default=1, validators=django.core.validators.MinValueValidator(1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='uuid',
            field=models.UUIDField(default='556cfe1b-a4d5-4e39-b72e-60bb419975d4'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('uuid', 'rev')]),
        ),
    ]
