# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20170310_2225'),
        ('jobs', '0002_auto_20170314_2249'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='job',
            index_together=set([('stream', 'uuid', 'rev')]),
        ),
    ]
