# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
