# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommcarehqCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('api_key', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CommcarehqInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('commcarehq_domain', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='commcarehqcredential',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commcarehq.CommcarehqInstance'),
        ),
    ]
