# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commcarehq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commcarehqinstance',
            name='url',
            field=models.URLField(),
        ),
    ]
